### ISSUE TITLE
Can `index-to-selected` handle no selection?

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-converters#22]
http://canjs.com/doc/can-stache-converters.index-to-selected.html

Does the following work?

```
<select {($value)}="index-to-selected(~person, people)">
    <option value="-1">Select a person</option>
    {{#each people}}
        <option value="{{%index}}">{{name}}</option>
    {{/each}}
</select>
```

If not, we should make it work.  Otherwise we should document it.

**Comment by justinbmeyer** [comment]
Yeah, probably

**Comment by phillipskevin** [comment]
I think since this is working as expected (as confirmed by https://github.com/canjs/can-stache-converters/pull/54), we can close this issue.
