### ISSUE TITLE
Warn when global helpers overwrite each other.

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache-converters#24]
From @Alfredo-Delgado’s comments in Slack: https://bitovi.slack.com/archives/team-open-source/p1489619998859150

> ran into this on a project, had a *stache helper* named `not` which worked fine in dev mode, but when the app was built with `can-stache-converters`, its `not` *converter* took precedence and was crashing because it wasn't passed a compute

**Comment by Alfredo-Delgado** [comment]
One thing that stands out to me is that all the other converters have very specific hyphenated names like
- boolean-to-inList(item, list)
- string-to-any(~item)
- index-to-selected(~item, list)
- either-or(~chosen, a, b)

`not` would fit in better with a name like `boolean-to-inverse`

**Comment by justinbmeyer** [comment]
The name is sort of locked in now until 4.0. We should give warnings when a helper overwrites a other one.

**Comment by matthewp** [comment]
There must be some ordering issue going on that causes it to work differently in dev vs prod.

**Comment by christopherjbaker** [comment]
PR canjs/can-stache#193 adds a warning, I'm not sure how to try to track down the ordering difference though.

**Comment by phillipskevin** [comment]
The tests added in https://github.com/canjs/can-stache/pull/193 need to be skipped in production mode, since the warnings are removed in production.

**Comment by christopherjbaker** [comment]
Sorry about that. canjs/can-stache#210
