### ISSUE TITLE
reversed can-stache-converters?

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-converters#28]
With view-models, it's likely that we might want reverse converters:

```
<drivers-list 
    {^selected}="selected-to-index(~index, drivers)"/>
```

This also shows wanting to use it with {^toParent}, which we should make sure works.

**Comment by bmomberger-bitovi** [comment]
Also came across a use case where I wanted a class to be applied to an element based on the truthiness of a viewModel flag, but right now the closest converter to that use case (`either-or`) only works in the other direction.
