### ISSUE TITLE
#each() doesn’t work with select[multiple]

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache-converters#65]
Using the `#each()` call expression doesn’t seem to work in this demo: https://github.com/canjs/canjs/blob/54a8bb29e5e73447a9e434da78fe74dd3a37d66c/demos/can-stache-converters/multi-values.html#L47-L49

When it’s reverted to `{{#each colors}}`, the demo works correctly.

Version: `can-stache-converters@3.3.0`

**Comment by justinbmeyer** [comment]
I think this would be good to verify it's not fixed in 4.0.

**Comment by cherifGsoul** [comment]
This [Codepen](https://codepen.io/cherifGsoul/pen/oQaajr) demonstrate that issue had been fixed.
