### ISSUE TITLE
update docs to show there's no need for ~

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-converters#76]
Update the docs to reflect #68

**Comment by justinbmeyer** [comment]
For example:

> checked:bind="boolean-to-inList(~key, list)" cross-binds the checked property to key being added to / removed from list. The tilde (~) is important here because the compute it sets up acts as a channel between the element's property and the scope's property.

Talks about using ~.  It shouldn't.  All demos should be checked to make sure they don't use ~.

**Comment by justinbmeyer** [comment]
https://canjs.com/doc/can-stache-converters.html


> The tilde (~) is important here because the compute it sets up acts as a channel between the element's property and the scope's property.


https://canjs.com/doc/can-stache-converters.equal.html

> This removes the requirement that the first argument is converted to a compute with ~.

**Comment by michaelzcheng** [comment]
Resolved with #92
