### ISSUE TITLE
Some demos broken

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-converters#79]
On https://canjs.com/doc/can-stache-converters.boolean-to-inList.html, the demo is broken:

![image](https://user-images.githubusercontent.com/5851984/35742099-22c7ab42-07ff-11e8-9641-03e384fde8f0.png)

This is can-stache-converters@4.0.1.

The equal demo is also broken:

![image](https://user-images.githubusercontent.com/5851984/35742218-63ce4a56-07ff-11e8-9410-2a5079743bfe.png)

**Comment by justinbmeyer** [comment]
```
<p>You own: {{ownership}}</p>
```

->

```
<p>You own: {{ownership()}}</p>
```
