### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-converters#8]
- [x] - homepage doesn't have a signature or a very good overview. I thought the equivalent `can-value` demos would be listed.  This is what `pages` are for.  But we should let people know to look there.  Maybe "Pages" should be called "Examples".
- [x] - select and select[multiple] should probably be next to each other under _Pages_.
- [x] - boolean-to-inList should be made into a demo
- [x] - can-stache-converters.either-or
  - [x] - linking broken, 
  - [x] - not sure what " This converter is useful when you have a binary decision that your user will implicitly understand." means.
  - [x] - needs to be a demo
  - [x] - signature needs a comma here:  " if it is equal to a__,__ returns true" 
  - [x] - as a getter/setter bound to an element's property or attribute OR a component's viewModel.
- [x] - equal
  - [x] - are two signatures necessary?
  - [x] - convert to a demo.
- [x] - index-to-selected
  - [x] - demo JS indentation is messed up (on other demos too).
  - [x] - demo uses ES6 ... change to CJS
  - [x] - **P1** - Demo is broken.  If I change the name in the select, nothing happens.
  - [x] - _the index as the key._ as the key of what?  Maybe shorten to "A converter useful to select a value within a list of `<options>` within a `<select>` element.".
- [x] - can-stache-converters.pages-select-multiple
  - [x] - No HTML in demo (JS indentation too)
  - [x] - DEMO output doesn't show anything.  Broken?
- [x] - can-stache-converters.pages.input-checkbox
  - [x] - **P1** Linking broken: "[can-stache-converters provides a couple o"
  - [x] - Binding to checkboxes demo broken.

**Comment by justinbmeyer** [comment]
Note that only the broken demos are P1.  The rest of these issues are P2.

**Comment by matthewp** [comment]
> homepage doesn't have a signature or a very good overview. I thought the equivalent can-value demos would be listed. This is what pages are for. But we should let people know to look there. Maybe "Pages" should be called "Examples".

These don't actually belong in can-stache-converters as they don't use any converters. I think they should be moved to a Recipes section in Guides.

**Comment by phillipskevin** [comment]
@bmomberger-bitovi can this be closed?

**Comment by phillipskevin** [comment]
Going to close for now. If there is still work to be done, please reopen and we'll move it to the [CanJS 3.5.1 Epic](https://github.com/canjs/canjs/issues/3108).

**Comment by bmomberger-bitovi** [comment]
The PR for updating the demos was closed without merging for some reason.

**Comment by bmomberger-bitovi** [comment]
The PR with actual doc changes is still unreviewed/unmerged: https://github.com/canjs/can-stache-converters/pull/21
